### PR TITLE
Moving wiki content to the main repo

### PR DESCRIPTION
**Pull request by mperezv**
We decided to move the content of the wiki to this repo because this way we can check the content.

### CODE REVIEW

**Review by sauloperez — CHANGES_REQUESTED** [review]
I wouldn't create the wiki folder. It is redundant and doesn't solve the need to organize the files in topic folders.

**Comment by mperezv** [comment]
@sauloperez OK, that's logic. But we need a folder structure. What do you think about creating one folder for each topic on the wiki?

**Comment by mperezv** [comment]
Thinking about the structures we've noticed that the links will break if we change the paths.

**Comment by sauloperez** [comment]
> Thinking about the structures we've noticed that the links will break if we change the paths.

true. What if we start without folders so that we can keep using the handbook and then work on migrating folders and links? we could go with a pull request by folder. @raneq you might know best but I think a little bit of `sed` will do the trick, don't you think?

**Comment by sauloperez** [comment]
> Thinking about the structures we've noticed that the links will break if we change the paths.

true. What if we start without folders so that we can keep using the handbook and then work on migrating folders and links? we could go with a pull request by folder. @raneq you might know best but I think a little bit of `sed` will do the trick, don't you think?

**Comment by danypr92** [comment]
I think that the solution suggested by @sauloperez is a great step.
We can start without any structure and we can iterate over it.

**Pull request closed without merging**
